### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by loveJasmine** [ningshixian/NER-CONLL2003#2]
(.venv) mldl@ub1604:~/ub16_prj/NER-CONLL2003$ python3 main.py 
/home/mldl/v_py3tf1.3/.venv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
/home/mldl/v_py3tf1.3/.venv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/v_py3tf1.3/.venv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

获取索引字典......
Words in index:  30290
max sentence size is : 112
max sentence size is : 123
max sentence size is : 108
Shape of data  tensor: (204567, 5)
Shape of label tensor: (204567, 5)
Shape of data  tensor: (46666, 5)
Shape of label tensor: (46666, 5)
Shape of data  tensor: (51578, 5)
Shape of label tensor: (51578, 5)
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    model.add(Dense(num_classes, activation='softmax'))
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/engine/sequential.py", line 187, in add
    output_tensor = layer(self.outputs[0])
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/layers/core.py", line 889, in call
    output = self.activation(output)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/activations.py", line 29, in softmax
    return K.softmax(x)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 3149, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'
(.venv) mldl@ub1604:~/ub16_prj/NER-CONLL2003$

**Comment by loveJasmine** [comment]
which version of keras?

**Comment by ningshixian** [comment]
tf1.3和keras2.1

**Comment by loveJasmine** [comment]
it passed
