### ISSUE TITLE
NameError: name 'conlleval' is not defined

### ISSUE THREAD

**Issue by loveJasmine** [ningshixian/NER-CONLL2003#3]
1-0	None	None

in	None	None

their	None	None

group	None	None

qualifier	None	None

.	None	None

Traceback (most recent call last):
  File "main.py", line 377, in <module>
    validation_data=(x_test, y_test))
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/models.py", line 960, in fit
    validation_steps=validation_steps)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/engine/training.py", line 1648, in fit
    validation_steps=validation_steps)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/engine/training.py", line 1233, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/mldl/v_py3tf1.3/.venv/lib/python3.5/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "main.py", line 265, in on_epoch_end
    p, r, f, c = predictLabels1(target, self.y_test, y_pred)
  File "main.py", line 299, in predictLabels1
    p, r, f, c = conlleval.main((None, r'results/result.txt'))
NameError: name 'conlleval' is not defined

**Comment by ningshixian** [comment]
You need to check if the path of conlleval.py is imported correctly.

**Comment by loveJasmine** [comment]
many other tiny bugs
